# Spring Boot configuration for PDFalyzer Studio

# server
server.port=8080

# thymeleaf
spring.thymeleaf.cache=false

# multipart upload limits
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# session
server.servlet.session.timeout=30m

# logging
logging.level.root=INFO
logging.level.io.pdfalyzer=DEBUG
logging.level.io.pdfalyzer.client-errors=INFO
logging.level.org.apache.pdfbox.pdmodel.interactive.form.PDSignatureField=ERROR
logging.level.org.apache.pdfbox.pdmodel.font.PDType0Font=ERROR
